/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package POSystem;

/**
 *
 * @author Hashim
 */
import javafx.scene.input.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;


public class POSystem extends javax.swing.JFrame {

    /**
     * Creates new form POSystem
     */
    
     String iTax, iSubtotal, iTotal;
     double tax, subtotal;
     double itemsCost [] = new double[14];
    
    
    public POSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtnApple = new javax.swing.JButton();
        jbtnpineapple = new javax.swing.JButton();
        JbtnOrange = new javax.swing.JButton();
        jbtnSmokie = new javax.swing.JButton();
        jtbnPassion = new javax.swing.JButton();
        jtbnBanana = new javax.swing.JButton();
        jbtnAvocado = new javax.swing.JButton();
        jtbGuava = new javax.swing.JButton();
        jbtnMelon = new javax.swing.JButton();
        jtbnLemon = new javax.swing.JButton();
        jbtnBread = new javax.swing.JButton();
        jtbnBacon = new javax.swing.JButton();
        jbtnButter = new javax.swing.JButton();
        jbtnPeanuts = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jcboxOrange = new javax.swing.JCheckBox();
        jtxtorange = new javax.swing.JTextField();
        jcboxApple = new javax.swing.JCheckBox();
        jtxtApple = new javax.swing.JTextField();
        jcboxPineapple = new javax.swing.JCheckBox();
        jtxtPineapple = new javax.swing.JTextField();
        jcboxbanana = new javax.swing.JCheckBox();
        jtxtBanana = new javax.swing.JTextField();
        jcboxGuava = new javax.swing.JCheckBox();
        jcboxPassion = new javax.swing.JCheckBox();
        jtxtPassion = new javax.swing.JTextField();
        jtxtGuava = new javax.swing.JTextField();
        jcboxLemon = new javax.swing.JCheckBox();
        jcboxAvocado = new javax.swing.JCheckBox();
        jtxtAvocado = new javax.swing.JTextField();
        jtxtlemon = new javax.swing.JTextField();
        jcboxSmokie = new javax.swing.JCheckBox();
        jtxtsmokie = new javax.swing.JTextField();
        jtxtMelon = new javax.swing.JTextField();
        jcboxMelon = new javax.swing.JCheckBox();
        jcboxBacon = new javax.swing.JCheckBox();
        jtxtBacon = new javax.swing.JTextField();
        jcboxBread = new javax.swing.JCheckBox();
        jtxtbread = new javax.swing.JTextField();
        jcboxPeanuts = new javax.swing.JCheckBox();
        jtxtButter = new javax.swing.JTextField();
        jtxtpeanuts = new javax.swing.JTextField();
        jcboxbutter = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jbtnTax = new javax.swing.JButton();
        jtxtTax = new javax.swing.JTextField();
        jbtnSubtotal = new javax.swing.JButton();
        jtxtSubtotal = new javax.swing.JTextField();
        jbtnTotal = new javax.swing.JButton();
        jtxtTotal = new javax.swing.JTextField();
        jbtnExit = new javax.swing.JButton();
        jbtnRun = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceiptArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("SDG Store");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jbtnApple.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnApple.setText("Apple");
        jbtnApple.setHideActionText(true);
        jbtnApple.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAppleActionPerformed(evt);
            }
        });

        jbtnpineapple.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnpineapple.setText("Pineapple");
        jbtnpineapple.setHideActionText(true);
        jbtnpineapple.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnpineapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpineappleActionPerformed(evt);
            }
        });

        JbtnOrange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JbtnOrange.setText("Orange");
        JbtnOrange.setHideActionText(true);
        JbtnOrange.setPreferredSize(new java.awt.Dimension(100, 35));
        JbtnOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnOrangeActionPerformed(evt);
            }
        });

        jbtnSmokie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSmokie.setText("Smokie");
        jbtnSmokie.setHideActionText(true);
        jbtnSmokie.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnSmokie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSmokieActionPerformed(evt);
            }
        });

        jtbnPassion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtbnPassion.setText("Passion");
        jtbnPassion.setHideActionText(true);
        jtbnPassion.setPreferredSize(new java.awt.Dimension(100, 35));
        jtbnPassion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnPassionActionPerformed(evt);
            }
        });

        jtbnBanana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtbnBanana.setText("Banana");
        jtbnBanana.setHideActionText(true);
        jtbnBanana.setPreferredSize(new java.awt.Dimension(100, 35));
        jtbnBanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnBananaActionPerformed(evt);
            }
        });

        jbtnAvocado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnAvocado.setText("Avocado");
        jbtnAvocado.setHideActionText(true);
        jbtnAvocado.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnAvocado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAvocadoActionPerformed(evt);
            }
        });

        jtbGuava.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtbGuava.setText("Guava");
        jtbGuava.setHideActionText(true);
        jtbGuava.setPreferredSize(new java.awt.Dimension(100, 35));
        jtbGuava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbGuavaActionPerformed(evt);
            }
        });

        jbtnMelon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnMelon.setText("Melon");
        jbtnMelon.setHideActionText(true);
        jbtnMelon.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnMelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMelonActionPerformed(evt);
            }
        });

        jtbnLemon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtbnLemon.setText("Lemon");
        jtbnLemon.setHideActionText(true);
        jtbnLemon.setPreferredSize(new java.awt.Dimension(100, 35));
        jtbnLemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnLemonActionPerformed(evt);
            }
        });

        jbtnBread.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnBread.setText("Bread");
        jbtnBread.setHideActionText(true);
        jbtnBread.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnBread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBreadActionPerformed(evt);
            }
        });

        jtbnBacon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtbnBacon.setText("Bacon");
        jtbnBacon.setHideActionText(true);
        jtbnBacon.setPreferredSize(new java.awt.Dimension(100, 35));
        jtbnBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnBaconActionPerformed(evt);
            }
        });

        jbtnButter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnButter.setText("Butter");
        jbtnButter.setHideActionText(true);
        jbtnButter.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnButter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnButterActionPerformed(evt);
            }
        });

        jbtnPeanuts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPeanuts.setText("Peanuts");
        jbtnPeanuts.setHideActionText(true);
        jbtnPeanuts.setPreferredSize(new java.awt.Dimension(100, 35));
        jbtnPeanuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPeanutsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnApple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnpineapple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnPassion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAvocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMelon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnBacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnButter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSmokie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbGuava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnBanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnLemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPeanuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnApple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnpineapple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnBanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbnPassion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbGuava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAvocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnLemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMelon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSmokie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbnBacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPeanuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnButter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(383, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 500));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jcboxOrange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxOrange.setText("Orange");
        jcboxOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxOrangeActionPerformed(evt);
            }
        });

        jtxtorange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtorange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtorange.setText("0");
        jtxtorange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtorangeActionPerformed(evt);
            }
        });
        jtxtorange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtorangeKeyTyped(evt);
            }
        });

        jcboxApple.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcboxApple.setText("Apple");
        jcboxApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxAppleActionPerformed(evt);
            }
        });

        jtxtApple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtApple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtApple.setText("0");
        jtxtApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAppleActionPerformed(evt);
            }
        });
        jtxtApple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAppleKeyTyped(evt);
            }
        });

        jcboxPineapple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxPineapple.setText("Pineapple");
        jcboxPineapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxPineappleActionPerformed(evt);
            }
        });

        jtxtPineapple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtPineapple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPineapple.setText("0");
        jtxtPineapple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPineappleKeyTyped(evt);
            }
        });

        jcboxbanana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxbanana.setText("Banana");
        jcboxbanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxbananaActionPerformed(evt);
            }
        });

        jtxtBanana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtBanana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBanana.setText("0");
        jtxtBanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBananaActionPerformed(evt);
            }
        });
        jtxtBanana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBananaKeyTyped(evt);
            }
        });

        jcboxGuava.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxGuava.setText("Guava");
        jcboxGuava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxGuavaActionPerformed(evt);
            }
        });

        jcboxPassion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxPassion.setText("Passion");
        jcboxPassion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxPassionActionPerformed(evt);
            }
        });

        jtxtPassion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtPassion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPassion.setText("0");
        jtxtPassion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPassionKeyTyped(evt);
            }
        });

        jtxtGuava.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtGuava.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtGuava.setText("0");
        jtxtGuava.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtGuavaKeyTyped(evt);
            }
        });

        jcboxLemon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxLemon.setText("Lemon");
        jcboxLemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxLemonActionPerformed(evt);
            }
        });

        jcboxAvocado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxAvocado.setText("Avocado");
        jcboxAvocado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxAvocadoActionPerformed(evt);
            }
        });

        jtxtAvocado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtAvocado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtAvocado.setText("0");
        jtxtAvocado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAvocadoKeyTyped(evt);
            }
        });

        jtxtlemon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtlemon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlemon.setText("0");
        jtxtlemon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtlemonKeyTyped(evt);
            }
        });

        jcboxSmokie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxSmokie.setText("Smokie");
        jcboxSmokie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxSmokieActionPerformed(evt);
            }
        });

        jtxtsmokie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtsmokie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsmokie.setText("0");
        jtxtsmokie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsmokieActionPerformed(evt);
            }
        });
        jtxtsmokie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtsmokieKeyTyped(evt);
            }
        });

        jtxtMelon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtMelon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMelon.setText("0");
        jtxtMelon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMelonKeyTyped(evt);
            }
        });

        jcboxMelon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxMelon.setText("Melon");
        jcboxMelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxMelonActionPerformed(evt);
            }
        });

        jcboxBacon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxBacon.setText("Bacon");
        jcboxBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxBaconActionPerformed(evt);
            }
        });

        jtxtBacon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtBacon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBacon.setText("0");
        jtxtBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBaconActionPerformed(evt);
            }
        });
        jtxtBacon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBaconKeyTyped(evt);
            }
        });

        jcboxBread.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxBread.setText("Bread");
        jcboxBread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxBreadActionPerformed(evt);
            }
        });

        jtxtbread.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtbread.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtbread.setText("0");
        jtxtbread.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtbreadKeyTyped(evt);
            }
        });

        jcboxPeanuts.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxPeanuts.setText("Peanuts");
        jcboxPeanuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxPeanutsActionPerformed(evt);
            }
        });

        jtxtButter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtButter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtButter.setText("0");
        jtxtButter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtButterActionPerformed(evt);
            }
        });
        jtxtButter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtButterKeyTyped(evt);
            }
        });

        jtxtpeanuts.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtpeanuts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpeanuts.setText("0");
        jtxtpeanuts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtpeanutsKeyTyped(evt);
            }
        });

        jcboxbutter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcboxbutter.setText("Butter");
        jcboxbutter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxbutterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcboxApple, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcboxPineapple))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtApple)
                            .addComponent(jtxtPineapple, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcboxAvocado)
                            .addComponent(jcboxMelon)
                            .addComponent(jcboxBacon)
                            .addComponent(jcboxbutter))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtButter, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jtxtBacon)
                            .addComponent(jtxtMelon)
                            .addComponent(jtxtAvocado)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jcboxPassion)
                        .addGap(40, 40, 40)
                        .addComponent(jtxtPassion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcboxbanana, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxGuava, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxBread, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxSmokie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxLemon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxPeanuts, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtBanana, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtorange, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtGuava, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtlemon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtsmokie, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtbread, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtpeanuts, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboxApple)
                    .addComponent(jtxtApple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxOrange)
                    .addComponent(jtxtorange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboxPineapple)
                    .addComponent(jtxtPineapple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxbanana)
                    .addComponent(jtxtBanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboxPassion)
                    .addComponent(jtxtPassion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxGuava)
                    .addComponent(jtxtGuava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboxAvocado)
                    .addComponent(jtxtAvocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxLemon)
                    .addComponent(jtxtlemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboxMelon)
                    .addComponent(jtxtMelon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxSmokie)
                    .addComponent(jtxtsmokie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboxBacon)
                    .addComponent(jtxtBacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboxBread)
                    .addComponent(jtxtbread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcboxbutter)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtButter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcboxPeanuts)
                        .addComponent(jtxtpeanuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jbtnTax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnTax.setText("Tax");
        jbtnTax.setPreferredSize(new java.awt.Dimension(120, 40));
        jbtnTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTaxActionPerformed(evt);
            }
        });

        jtxtTax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jbtnSubtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSubtotal.setText("Subtotal");
        jbtnSubtotal.setPreferredSize(new java.awt.Dimension(120, 40));
        jbtnSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubtotalActionPerformed(evt);
            }
        });

        jtxtSubtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSubtotal.setText("0");
        jtxtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubtotalActionPerformed(evt);
            }
        });

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.setPreferredSize(new java.awt.Dimension(120, 40));
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotal.setText("0");
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setPreferredSize(new java.awt.Dimension(120, 40));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnRun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnRun.setText("Run");
        jbtnRun.setPreferredSize(new java.awt.Dimension(120, 40));
        jbtnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRunActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setPreferredSize(new java.awt.Dimension(120, 40));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jtxtReceiptArea.setColumns(20);
        jtxtReceiptArea.setRows(5);
        jScrollPane1.setViewportView(jtxtReceiptArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(228, 228, 228))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("Cost of Item and Receipt");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcboxOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxOrangeActionPerformed
       if(jcboxOrange.isSelected()){
           jtxtorange.setEnabled(true);
           jtxtorange.setText("");
           jtxtorange.requestFocus();
       }else {
           jtxtorange.setEnabled(false);
           jtxtorange.setText("0");
       }
    }//GEN-LAST:event_jcboxOrangeActionPerformed

    private void JbtnOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnOrangeActionPerformed
        //jtxtorange.setEnabled(true);
        jcboxOrange.setEnabled(true);
    }//GEN-LAST:event_JbtnOrangeActionPerformed

    private void jtbGuavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbGuavaActionPerformed
        jcboxGuava.setEnabled(true);
        //jtxtGuava.setEnabled(true);
    }//GEN-LAST:event_jtbGuavaActionPerformed

    private void jtxtBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBaconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBaconActionPerformed

    private void jcboxbutterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxbutterActionPerformed
        if(jcboxbutter.isSelected()){
            jtxtButter.setEnabled(true);
            jtxtButter.setText("");
            jtxtButter.requestFocus();
        }else {
            jtxtButter.setEnabled(false);
            jtxtButter.setText("0");
        }
    }//GEN-LAST:event_jcboxbutterActionPerformed

    private void jtxtButterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtButterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtButterActionPerformed

    private void jtxtorangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtorangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtorangeActionPerformed

    private void jtxtBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBananaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBananaActionPerformed

    private void jtxtsmokieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsmokieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsmokieActionPerformed

    private void jcboxBreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxBreadActionPerformed
        if(jcboxBread.isSelected()){
            jtxtbread.setEnabled(true);
            jtxtbread.setText("");
            jtxtbread.requestFocus();
        }else {
            jtxtbread.setEnabled(false);
            jtxtbread.setText("0");
        }
    }//GEN-LAST:event_jcboxBreadActionPerformed

    private void jbtnTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTaxActionPerformed
        
        jtxtTax.setText(iTax);
        
        
    }//GEN-LAST:event_jbtnTaxActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jbtnSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubtotalActionPerformed
        // TODO smn
        
    }//GEN-LAST:event_jbtnSubtotalActionPerformed

    private void jtxtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubtotalActionPerformed
       
       
    }//GEN-LAST:event_jtxtSubtotalActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // Do Something bruh!!      
    }//GEN-LAST:event_jbtnTotalActionPerformed

  private JFrame theFrame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        theFrame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(theFrame, "Please Confirm you want to exit", "Point of Sale", JOptionPane.YES_NO_OPTION)== 
        JOptionPane.YES_NO_OPTION){
         System.exit(0);
        }
        
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRunActionPerformed
        // TODO add your handling code here:
        itemsCost[0] = Double.parseDouble(jtxtApple.getText())* 30.00;
        itemsCost[1] = Double.parseDouble(jtxtorange.getText())* 15.00;
        itemsCost[2] = Double.parseDouble(jtxtAvocado.getText())* 20.00;
        itemsCost[3] = Double.parseDouble(jtxtBanana.getText())* 10.00;
        itemsCost[4] = Double.parseDouble(jtxtPineapple.getText())* 120.00;
        itemsCost[5] = Double.parseDouble(jtxtPassion.getText())* 5.00;
        itemsCost[6] = Double.parseDouble(jtxtGuava.getText())* 6.00;
        itemsCost[7] = Double.parseDouble(jtxtlemon.getText())* 5.00;
        itemsCost[8] = Double.parseDouble(jtxtMelon.getText())* 180.00;
        itemsCost[9] = Double.parseDouble(jtxtsmokie.getText())* 25.00;
        itemsCost[10] = Double.parseDouble(jtxtBacon.getText())* 110.00;
        itemsCost[11] = Double.parseDouble(jtxtpeanuts.getText())* 35.00;
        itemsCost[12] = Double.parseDouble(jtxtbread.getText())* 50.00;
        
        double total = 0;
       
        for(int i = 0; i < itemsCost.length; i++){
            total += itemsCost[i];
        }
        
        tax = total * (double) 16 / 100;
        subtotal = total;
        
        iSubtotal = String.format("Sh. %.2f", total);
        jtxtSubtotal.setEnabled(true);
        jtxtSubtotal.setText(iSubtotal);
        jtxtSubtotal.setEditable(false);
        
        iTax = String.format("Sh. %.2f", tax);
        jtxtTax.setEnabled(true);
        jtxtTax.setText(iTax);
        jtxtTax.setEditable(false);
        
        iTotal = String.format("Sh. %.2f", (tax + subtotal));
        jtxtTotal.setEnabled(true);
        jtxtTotal.setText(iTotal);
        jtxtTotal.setEditable(false);
        
        jtxtReceiptArea.setEnabled(true);
        
        int refNumber = 838 + (int) (Math.random()*4888);
        
        
        //Setting the Time
        Calendar timer = Calendar.getInstance();
        SimpleDateFormat tformat = new SimpleDateFormat("HH:mm:ss");
        tformat.format(timer.getTime());
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-mm-yyyy");
        dFormat.format(timer.getTime());
        
        
    }//GEN-LAST:event_jbtnRunActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
       jtxtApple.setText("");
       jcboxApple.setSelected(false);
       
       
       jcboxApple.setEnabled(false);
       jcboxAvocado.setEnabled(false);
       jcboxBacon.setEnabled(false);
       jcboxBread.setEnabled(false);
       jcboxGuava.setEnabled(false);
       jcboxLemon.setEnabled(false);
       jcboxPineapple.setEnabled(false);
       jcboxMelon.setEnabled(false);
       jcboxOrange.setEnabled(false);
       jcboxPassion.setEnabled(false);
       jcboxPeanuts.setEnabled(false);
       jcboxSmokie.setEnabled(false);
       jcboxbanana.setEnabled(false);
       jcboxbutter.setEnabled(false);
       
       
       jtxtApple.setEnabled(false);
        jtxtAvocado.setEnabled(false);
        jtxtorange.setEnabled(false);
        jtxtBacon.setEnabled(false);
        jtxtBanana.setEnabled(false);
        jtxtButter.setEnabled(false);
        jtxtlemon.setEnabled(false);
        jtxtPassion.setEnabled(false);
        jtxtbread.setEnabled(false);
        jtxtsmokie.setEnabled(false);
        jtxtTotal.setEnabled(false);
        jtxtSubtotal.setEnabled(false);
        jtxtTax.setEnabled(false);
        jtxtpeanuts.setEnabled(false);
        jtxtPineapple.setEnabled(false);
        jtxtGuava.setEnabled(false);
        jtxtReceiptArea.setEnabled(false);
        jtxtMelon.setEnabled(false);
       
       jtxtApple.setText("0");
       jcboxApple.setSelected(false);
       
       jtxtAvocado.setText("0");
       jcboxAvocado.setSelected(false);
       
       jtxtorange.setText("0");
       jcboxOrange.setSelected(false);
       
       jtxtBanana.setText("0");
       jcboxbanana.setSelected(false);
      
       jtxtPineapple.setText("0");
       jcboxPineapple.setSelected(false);
       
       jtxtPassion.setText("0");
       jcboxPassion.setSelected(false);
       
       jtxtGuava.setText("0");
       jcboxGuava.setSelected(false);
       
       jtxtlemon.setText("0");
       jcboxLemon.setSelected(false);
       
       jtxtMelon.setText("0");
       jcboxMelon.setSelected(false);
       
       jtxtsmokie.setText("0");
       jcboxSmokie.setSelected(false);
       
       jtxtBacon.setText("0");
       jcboxBacon.setSelected(false);
       
       jtxtbread.setText("0");
       jcboxBread.setSelected(false);
       
       jtxtButter.setText("0");
       jcboxbutter.setSelected(false);
       
       jtxtpeanuts.setText("0");
       jcboxPeanuts.setSelected(false);
       
       jtxtSubtotal.setText("0");
       jtxtTotal.setText("0");
       jtxtTax.setText("0");
       
       
       jtxtReceiptArea.setText("");
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtAppleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAppleKeyTyped
       char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtAppleKeyTyped

    private void jtxtorangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtorangeKeyTyped
        char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtorangeKeyTyped

    private void jtxtBananaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBananaKeyTyped
        char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtBananaKeyTyped

    private void jtxtPineappleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPineappleKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtPineappleKeyTyped

    private void jtxtPassionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPassionKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtPassionKeyTyped

    private void jtxtGuavaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGuavaKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtGuavaKeyTyped

    private void jtxtAvocadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAvocadoKeyTyped
        char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtAvocadoKeyTyped

    private void jtxtlemonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtlemonKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtlemonKeyTyped

    private void jtxtMelonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMelonKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtMelonKeyTyped

    private void jtxtsmokieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsmokieKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtsmokieKeyTyped

    private void jtxtBaconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBaconKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtBaconKeyTyped

    private void jtxtbreadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbreadKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtbreadKeyTyped

    private void jtxtButterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtButterKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtButterKeyTyped

    private void jtxtpeanutsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpeanutsKeyTyped
         char iNumber = evt.getKeyChar();
       if(!(Character.isDigit(iNumber))||(iNumber == evt.VK_BACK_SPACE)||(iNumber == evt.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtpeanutsKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Disabling the textfields
        jtxtApple.setEnabled(false);
        jtxtAvocado.setEnabled(false);
        jtxtorange.setEnabled(false);
        jtxtBacon.setEnabled(false);
        jtxtBanana.setEnabled(false);
        jtxtButter.setEnabled(false);
        jtxtlemon.setEnabled(false);
        jtxtPassion.setEnabled(false);
        jtxtbread.setEnabled(false);
        jtxtsmokie.setEnabled(false);
        jtxtTotal.setEnabled(false);
        jtxtSubtotal.setEnabled(false);
        jtxtTax.setEnabled(false);
        jtxtpeanuts.setEnabled(false);
        jtxtPineapple.setEnabled(false);
        jtxtGuava.setEnabled(false);
        jtxtReceiptArea.setEnabled(false);
        jtxtMelon.setEnabled(false);
        
        //Disabling the checkboxes
        jcboxApple.setEnabled(false);
        jcboxAvocado.setEnabled(false);
        jcboxBacon.setEnabled(false);
        jcboxBread.setEnabled(false);
        jcboxGuava.setEnabled(false);
        jcboxLemon.setEnabled(false);
        jcboxPineapple.setEnabled(false);
        jcboxMelon.setEnabled(false);
        jcboxOrange.setEnabled(false);
        jcboxPassion.setEnabled(false);
        jcboxPeanuts.setEnabled(false);
        jcboxSmokie.setEnabled(false);
        jcboxbanana.setEnabled(false);
        jcboxbutter.setEnabled(false);
        
        jbtnTax.setEnabled(false);
        jbtnSubtotal.setEnabled(false);
        jbtnTotal.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jbtnAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAppleActionPerformed
        jcboxApple.setEnabled(true);
    }//GEN-LAST:event_jbtnAppleActionPerformed

    private void jbtnpineappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpineappleActionPerformed
        jcboxPineapple.setEnabled(true);
    }//GEN-LAST:event_jbtnpineappleActionPerformed

    private void jtbnBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnBananaActionPerformed
        //jtxtBanana.setEnabled(true);
        jcboxbanana.setEnabled(true);
    }//GEN-LAST:event_jtbnBananaActionPerformed

    private void jtbnPassionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnPassionActionPerformed
        //jtxtPassion.setEnabled(true);
        jcboxPassion.setEnabled(true);
    }//GEN-LAST:event_jtbnPassionActionPerformed

    private void jbtnAvocadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAvocadoActionPerformed
        jcboxAvocado.setEnabled(true);
        //jtxtAvocado.setEnabled(true);
    }//GEN-LAST:event_jbtnAvocadoActionPerformed

    private void jtbnLemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnLemonActionPerformed
        jcboxLemon.setEnabled(true);
        //jtxtlemon.setEnabled(true);
    }//GEN-LAST:event_jtbnLemonActionPerformed

    private void jbtnMelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMelonActionPerformed
       //jtxtMelon.setEnabled(true);
        jcboxMelon.setEnabled(true);
    }//GEN-LAST:event_jbtnMelonActionPerformed

    private void jbtnSmokieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSmokieActionPerformed
        jcboxSmokie.setEnabled(true);
        //jtxtsmokie.setEnabled(true);
    }//GEN-LAST:event_jbtnSmokieActionPerformed

    private void jtbnBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnBaconActionPerformed
        jcboxBacon.setEnabled(true);
        //jtxtBacon.setEnabled(true);
    }//GEN-LAST:event_jtbnBaconActionPerformed

    private void jbtnBreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBreadActionPerformed
        jcboxBread.setEnabled(true);
        //jtxtbread.setEnabled(true);
    }//GEN-LAST:event_jbtnBreadActionPerformed

    private void jbtnButterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnButterActionPerformed
        jcboxbutter.setEnabled(true);
        //jtxtButter.setEnabled(true);
    }//GEN-LAST:event_jbtnButterActionPerformed

    private void jbtnPeanutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPeanutsActionPerformed
        jcboxPeanuts.setEnabled(true);
        //jtxtpeanuts.setEnabled(true);
    }//GEN-LAST:event_jbtnPeanutsActionPerformed

    private void jcboxAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxAppleActionPerformed
        if(jcboxApple.isSelected()){
            jtxtApple.setEnabled(true);
            jtxtApple.setText("");
            jtxtApple.requestFocus();
        }else {
            jtxtApple.setEnabled(false);
            jtxtApple.setText("0");
        }
    }//GEN-LAST:event_jcboxAppleActionPerformed

    private void jcboxPineappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxPineappleActionPerformed
       if (jcboxPineapple.isSelected()){
           jtxtPineapple.setEnabled(true);
           jtxtPineapple.setText("");
           jtxtPineapple.requestFocus();
       }else {
           jtxtPineapple.setEnabled(false);
           jtxtPineapple.setText("0");
       }
    }//GEN-LAST:event_jcboxPineappleActionPerformed

    private void jcboxbananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxbananaActionPerformed
       if(jcboxbanana.isSelected()){
           jtxtBanana.setEnabled(true);
           jtxtBanana.setText("");
           jtxtBanana.requestFocus();
       }else {
           jtxtBanana.setEnabled(false);
           jtxtBanana.setText("0");
       }
    }//GEN-LAST:event_jcboxbananaActionPerformed

    private void jcboxPassionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxPassionActionPerformed
        if(jcboxPassion.isSelected()){
            jtxtPassion.setEnabled(true);
            jtxtPassion.setText("");
            jtxtPassion.requestFocus();
        }else {
            jtxtPassion.setEnabled(false);
            jtxtPassion.setText("0");
        }
    }//GEN-LAST:event_jcboxPassionActionPerformed

    private void jcboxGuavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxGuavaActionPerformed
       if(jcboxGuava.isSelected()){
           jtxtGuava.setEnabled(true);
           jtxtGuava.setText("");
           jtxtGuava.requestFocus();
       }else {
           jtxtGuava.setEnabled(false);
           jtxtGuava.setText("0");
       }
    }//GEN-LAST:event_jcboxGuavaActionPerformed

    private void jcboxAvocadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxAvocadoActionPerformed
       if(jcboxAvocado.isSelected()){
           jtxtAvocado.setEnabled(true);
           jtxtAvocado.setText("");
           jtxtAvocado.requestFocus();
       }else {
           jtxtAvocado.setEnabled(false);
           jtxtAvocado.setText("0");
       }
    }//GEN-LAST:event_jcboxAvocadoActionPerformed

    private void jcboxLemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxLemonActionPerformed
        if(jcboxLemon.isSelected()){
            jtxtlemon.setEnabled(true);
            jtxtlemon.setText("");
            jtxtlemon.requestFocus();
        }else {
            jtxtlemon.setEnabled(false);
            jtxtlemon.setText("");
        }
    }//GEN-LAST:event_jcboxLemonActionPerformed

    private void jcboxMelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxMelonActionPerformed
        if(jcboxMelon.isSelected()){
            jtxtMelon.setEnabled(true);
            jtxtMelon.setText("");
            jtxtMelon.requestFocus();
        }else {
            jtxtMelon.setEnabled(false);
            jtxtMelon.setText("0");
        }
    }//GEN-LAST:event_jcboxMelonActionPerformed

    private void jcboxSmokieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxSmokieActionPerformed
       if(jcboxSmokie.isSelected()){
           jtxtsmokie.setEnabled(true);
           jtxtsmokie.setText("");
           jtxtsmokie.requestFocus();
       }else {
           jtxtsmokie.setEnabled(false);
           jtxtsmokie.setText("0");
       }
    }//GEN-LAST:event_jcboxSmokieActionPerformed

    private void jcboxBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxBaconActionPerformed
        if(jcboxBacon.isSelected()){
            jtxtBacon.setEnabled(true);
            jtxtBacon.setText("");
            jtxtBacon.requestFocus();
        }else {
            jtxtBacon.setEnabled(false);
            jtxtBacon.setText("0"); 
        }
    }//GEN-LAST:event_jcboxBaconActionPerformed

    private void jcboxPeanutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxPeanutsActionPerformed
       if(jcboxPeanuts.isSelected()){
           jtxtpeanuts.setEnabled(true);
           jtxtpeanuts.setText("");
           jtxtpeanuts.requestFocus();
       }else {
           jtxtpeanuts.setEnabled(false);
           jtxtpeanuts.setText("0");
       }
    }//GEN-LAST:event_jcboxPeanutsActionPerformed

    private void jtxtAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAppleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAppleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnOrange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnApple;
    private javax.swing.JButton jbtnAvocado;
    private javax.swing.JButton jbtnBread;
    private javax.swing.JButton jbtnButter;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnMelon;
    private javax.swing.JButton jbtnPeanuts;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnRun;
    private javax.swing.JButton jbtnSmokie;
    private javax.swing.JButton jbtnSubtotal;
    private javax.swing.JButton jbtnTax;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JButton jbtnpineapple;
    private javax.swing.JCheckBox jcboxApple;
    private javax.swing.JCheckBox jcboxAvocado;
    private javax.swing.JCheckBox jcboxBacon;
    private javax.swing.JCheckBox jcboxBread;
    private javax.swing.JCheckBox jcboxGuava;
    private javax.swing.JCheckBox jcboxLemon;
    private javax.swing.JCheckBox jcboxMelon;
    private javax.swing.JCheckBox jcboxOrange;
    private javax.swing.JCheckBox jcboxPassion;
    private javax.swing.JCheckBox jcboxPeanuts;
    private javax.swing.JCheckBox jcboxPineapple;
    private javax.swing.JCheckBox jcboxSmokie;
    private javax.swing.JCheckBox jcboxbanana;
    private javax.swing.JCheckBox jcboxbutter;
    private javax.swing.JButton jtbGuava;
    private javax.swing.JButton jtbnBacon;
    private javax.swing.JButton jtbnBanana;
    private javax.swing.JButton jtbnLemon;
    private javax.swing.JButton jtbnPassion;
    private javax.swing.JTextField jtxtApple;
    private javax.swing.JTextField jtxtAvocado;
    private javax.swing.JTextField jtxtBacon;
    private javax.swing.JTextField jtxtBanana;
    private javax.swing.JTextField jtxtButter;
    private javax.swing.JTextField jtxtGuava;
    private javax.swing.JTextField jtxtMelon;
    private javax.swing.JTextField jtxtPassion;
    private javax.swing.JTextField jtxtPineapple;
    private javax.swing.JTextArea jtxtReceiptArea;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtbread;
    private javax.swing.JTextField jtxtlemon;
    private javax.swing.JTextField jtxtorange;
    private javax.swing.JTextField jtxtpeanuts;
    private javax.swing.JTextField jtxtsmokie;
    // End of variables declaration//GEN-END:variables
}
